apiVersion: v1
kind: Command
metadata:
  name: emoji
  label:
    en_US: Emoji Fusion
    zh_Hans: 表情融合
  description:
    en_US: Fuse two emojis into one via yunzhiapi.cn API
    zh_Hans: 通过云智 API 将两个 Emoji 表情融合为一个
spec:
execution:
  python:
    path: emoji.py
    attr: Emoji