apiVersion: v1
kind: Page
metadata:
  name: memory_graph
  label:
    en_US: Memory Graph
    zh_Hans: 记忆图谱
spec:
  path: index.html
execution:
  python:
    path: memory_graph.py
    attr: MemoryGraphPage
